# Generated by Django 3.2.7 on 2021-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(blank=True, max_length=25, null=True)),
                ('product_id', models.CharField(blank=True, max_length=25, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=25, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('salt_name', models.TextField(blank=True, null=True)),
                ('drug_form', models.CharField(blank=True, max_length=50, null=True)),
                ('Pack_size', models.CharField(blank=True, max_length=50, null=True)),
                ('strength', models.TextField(blank=True, null=True)),
                ('product_banned_flag', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
